apiVersion: v1
kind: Service
metadata:
  name: longhorn-svc-ingress
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: longhorn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-svc-ingress
            port:
              number: 80